version: 2

models:
  - name: stg_product_category_map
    columns:
      - name: productid
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: messageid


